### ISSUE TITLE
Add working example of manufacturer key attestation

### ISSUE THREAD

**Issue by mflaxman** [googleapis/python-kms#23]
I've switched to asymmetric encryption to solve my problems in https://github.com/googleapis/python-kms/issues/22, and so far I have the following working:
1. Generate asymmetric RSA key locally
2. Import key to google cloud HSM
3. Encrypt data locally with pubkey
4. Decrypt data with cloud HSM

This is all awesome, but I want to prove to users that their data is being secured as designed. I download the attestation  `verify_attestation.py` and it works well:
```bash
$ python3 verify_attestation.py test_key_ring-localkey4096rsa_hsm_key-1-cavium_v2_compressed-attestation.dat cloud-kms-prod-global-google.pem
Signature verified.
$ python3 verify_attestation.pytest_key_ring-localkey4096rsa_hsm_key-1-cavium_v2_compressed-attestation.dat cloud-kms-prod-global-cavium.pem
Signature verified.
```

I want to follow [these instructions](https://www.marvell.com/products/security-solutions/liquid-security-hsm-adapters-and-appliances/software-key-attestation.html) that are [linked in your docs](https://cloud.google.com/kms/docs/attest-key) but I'm getting errors in both the v1 and v2 script (I don't know which version of firmware Google's HSM is using, but both `parse_v1.py` and `parse_v2.py` are failing):
```bash
$ python2 parse_v1.py test_key_ring-localkey4096rsa_hsm_key-1-cavium_v2_compressed-attestation.dat 
Public Key Attestation
0x3c5ca99c: '\xcf\xfc\xfa\x1b\xd3\x15\xfa_?@\xad\xb0\xf0(\xe3\xfcw\x11\xed\xa2{\xfe\x14\x1eVh\xfep{\xd3f\xb3\xa0{E\xf3\x0f\xf5Yo_1\xfd\xde\x11\x0f%\x9e\xbe \xae?\x93\xed\xb3\xee\xad\\\x90{Q\xc0j\xfd\xea\x9d\x97\xb5\xbeO\xeb\xb7(\x89\xfc1\x81O%\x84\xeb\xce\x8e\x88g\xb9&\xda\xf7\x15\x83\x8d\xbf^\xd9>\xa1$.\xedx\x84\xc4\xddg.\xac\xd9\x12<\xdb\xdc~:\x9d\\W\x9b!\xff\xf1C\xe8\x83\xee\x9d\x00_\x06\xe7\x19+\x05\x00\x00'
Traceback (most recent call last):
  File "parse_v1.py", line 44, in <module>
    offset = parse(attest_data[_CAVIUM_ATTESTATION_ASYM_OFFSET:])
  File "parse_v1.py", line 29, in parse
    attr_type, attr_len = struct.unpack_from(TLV, attestation, 0)
struct.error: unpack_from requires a buffer of at least 8 bytes

$ python2 parse_v2.py test_key_ring-localkey4096rsa_hsm_key-1-cavium_v2_compressed-attestation.dat 
Symmetric Key Attestation
```

I'd love it if you could add a working script to this repo (similar to `verify_attestation.py`), but updating the docs with instructions to make the manufacturer's script work would accomplish the same goal.

Thanks!

**Comment by busunkim96** [comment]
@sethvargo Could you take a look?

**Comment by sethvargo** [comment]
Hmmm this predates me, and I haven't had time to dig into the implementation here. @bdhess can you help route this?

**Comment by mflaxman** [comment]
On second look, I assume it's only the `parse_v2.py` script that matters as `v2` is in the filename of the attention that I downloaded from Google (`test_key_ring-localkey4096rsa_hsm_key-1-cavium_v2_compressed-attestation.dat`).

It would make sense for google to only use the newer firmware (v2) in their HSMs, but [the docs](https://cloud.google.com/kms/docs/attest-key) specifically say to download both scripts:
<img width="882" alt="Screen Shot 2020-06-26 at 1 11 25 PM" src="https://user-images.githubusercontent.com/448644/85888171-aba2ff00-b7ae-11ea-8a2c-13220a993cdb.png">

**Comment by mflaxman** [comment]
I thought it might be because I'm using a key that I generated locally and loaded into the HSM (step 1 here: https://github.com/googleapis/python-kms/issues/23#issue-645949141), but I tried the same thing on a key generated by the HSM and get the same (non) result:

```bash
$ python2 parse_v2.py test_key_ring-4096rsa_oaep_sha256-1-cavium_v2_compressed-attestation.dat
Symmetric Key Attestation
```

The script I'm running is the one linked to in your docs:
```bash
$ curl https://www.marvell.com/content/dam/marvell/en/public-collateral/security-solutions/parse_v2.py > parse_v2.py
```

**Comment by bdhess** [comment]
Sorry for the confusion here.  I think the issue is that the attestation is compressed (gzip format), and either the script or the docs need an update.

If you can try decompressing it (e.g. with `gzip -d`), you ought to be able to verify it normally.

**Comment by mflaxman** [comment]
That worked, thanks @bdhess! I recommend updating the documentation to unzip the `.dat` file (it's a binary and not obviously zipped). Even better would be to add the example code from `parse_v2.py` and `verify_pubkey.py` to this repo.

---

What's the best place to submit issues/questions that are more about documentation than the python library specifically (although sometimes the two go together)?

For example, I'm wondering what google thinks about users performing their own asymmetric encryption locally with the pubkey (whose privkey is stored in Google's HSM)? There's an example from the docs [here](https://cloud.google.com/kms/docs/encrypt-decrypt-rsa) but I'm not sure it's used to show that it's possible or that it should be considered secure?:
```bash
$ openssl pkeyutl -in cleartext-data-input-file \
    -encrypt \
    -pubin \
    -inkey public-key-path \
    -pkeyopt rsa_padding_mode:oaep \
    -pkeyopt rsa_oaep_md:sha256 \
    -pkeyopt rsa_mgf1_md:sha256 \
    > encrypted-data-output-file
```

The obvious benefit is that it doesn't require connectivity/uptime for encryption (obviously decryption needs to query the HSM) but there are [lots of complaints](https://github.com/ETCDEVTeam/janus/issues/8) about using openssl for (symmetric) encryption.

**Comment by bdhess** [comment]
Glad you're unstuck @mflaxman and we'll have a look at what the best path is to improving the docs so that other users don't fall into the same trap you fell into.

We don't offer an RPC in the Cloud KMS service that allows for asymmetric encryption -- it's assumed that users will download the public key and perform encryption locally, in their programming language of choice, or using something like openssl at the command line.  We've taken care to document that in a number of different ways.  Asymmetric decryption, on the other hand, must *always* happen in the service, since private keys are not extractable from Cloud KMS.

For symmetric encryption, there's no parallel choice or potential for confusion, because the secret key is also not extractable from Cloud KMS.  With symmetric keys, and encryption *and* decryption always happen in the KMS service.

The best way to make suggestions on any Cloud KMS documentation you see is to click the "Send Feedback" link at the bottom of one of our documentation pages.  That gets routed directly to our docs team, and they're great at tracking down issues and getting our docs updated in a timely manner.

**Comment by mflaxman** [comment]
Thanks @bdhess!

Lol, I didn't even think to click the other code-sample tabs! I've been doing almost everything at the command line. I was able to get this script for asymmetric encryption working, but I wouldn't trust it as much as your code sample that uses the awesome `pyca/cryptography` library. One nice thing about my code is that it's pure python and doesn't require `openssl` or any third party dependencies.

```
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Hash import SHA256

SECRET = b"Attack at dawn!"

PEM = """-----BEGIN PUBLIC KEY-----
YOUR KEY HERE
-----END PUBLIC KEY-----"""

rsa_pubkey = RSA.importKey(PEM)
pkcs = PKCS1_OAEP.new(rsa_pubkey, SHA256)
ciphertext = pkcs.encrypt(SECRET)

with open("/path/to/secret.enc", "wb") as f:
    f.write(ciphertext)
```

It's a bummer there's no PHP or Ruby support. I was really hoping https://github.com/google/tink would solve this problem but they don't support RSA with OAEP in any language just yet :(

> Asymmetric decryption, on the other hand, must always happen in the service, since private keys are not extractable from Cloud KMS.

I've been testing loading keys into the HSM that I generated locally, so for that use-case I can decrypt locally as well as in the HSM. That's an acceptable use, right? Just want to be sure I'm not doing something that's going to be disabled in the future. The attestation does correctly display that the key in the HSM was not generated there. There are customers who want that (guaranteed backup/portability as well as ability to decrypt without revealing their plaintext to third parties) as well as those who explicitly don't (having copies of keys live outside of an HSM increases the risk they are compromised).

**Comment by bdhess** [comment]
This imports look like the [Pycrypto module](https://pypi.org/project/pycrypto/), which is [no longer maintained](https://github.com/pycrypto/pycrypto/issues/173).  There are forks that are being maintained like [Pycryptodome](https://pycryptodome.readthedocs.io/).  But to be honest, we're not familiar with any of them, nor have we reviewed them for trustworthiness.

We're reasonably familiar with OpenSSL and Pyca cryptography, and despite the tradeoff of it having a native dependency, it's the thing we're most comfortable recommending.  But if you're happy with Pycrypto or one of its descendants, don't let us dissuade you. :-)

> I've been testing loading keys into the HSM that I generated locally, so for that use-case I can decrypt locally as well as in the HSM. That's an acceptable use, right?

Yep, key import is fully supported and is not going away.  Just-- if you're going to build a process that does asymmetric decryption offline, it's not clear why you'd bother importing the key into KMS at all, because we don't offer asymmetric encryption functionality in the service.  The typical use case for importing an asymmetric key is for key backup/archival and that sort of thing; not to actually build processes that wield the key outside the service.

**Comment by vchudnov-g** [comment]
@mflaxman Is this still an issue?
