### ISSUE TITLE
`list_key_rings` documentation refers to `location_path` for KeyManagementServiceClient()

### ISSUE THREAD

**Issue by meangrape** [googleapis/python-kms#343]
The [documentation](https://cloud.google.com/python/docs/reference/cloudkms/1.3.0/google.cloud.kms_v1.KeyManagementServiceClient#google_cloud_kms_v1_KeyManagementServiceClient_list_key_rings) for `list_key_rings` has the following example code:

```python
from google.cloud import kms_v1
client = kms_v1.KeyManagementServiceClient()
parent = client.location_path('[PROJECT]', '[LOCATION]')
for element in client.list_key_rings(parent): ... # process element ... pass
```

`KeyManagementServiceClient` does not have a `location_path`.

The example code should look like:

```python
from google.cloud import kms_v1
client = kms_v1.KeyManagementServiceClient()
parent = 'projects/*/locations/*'
request = kms_v1.ListKeyRingsRequest(parent=parent)
result = client.list_key_rings(request=request)

for element in result:
    # process element
    pass
```

**Comment by parthea** [comment]
Hi @meangrape ,

Thanks for reporting this issue. The linked documentation is for version 1.3.0 which was released in February 2020. We've updated the docs since that release and we recommend that you use the latest version of the docs:

https://cloud.google.com/kms/docs/samples/kms-quickstart
https://cloud.google.com/python/docs/reference/cloudkms/latest/google.cloud.kms_v1.services.key_management_service.KeyManagementServiceClient#google_cloud_kms_v1_services_key_management_service_KeyManagementServiceClient_list_key_rings
