### ISSUE TITLE
Disabling a crypto key

### ISSUE THREAD

**Issue by BinarSkugga** [googleapis/python-kms#91]
I can't seem to find a way to disable an entire crypto key. The documentation says that disabling a key should disable all its version but I can't update the state of a crypto key. Is this even possible ? The UI seems to have the option but thats it. Its an issue because disabling all the versions one by one makes me hit the read and write request quota per minute for key versions.

**Comment by busunkim96** [comment]
Hi @BinarSkugga,

@bdhess is there a way to disable multiple crypto key versions in a single request?

**Comment by parthea** [comment]
I'm going to close this issue as sample code is available to disable a crypto key: https://cloud.google.com/kms/docs/enable-disable#kms-disable-key-version-python. Regarding the ability to disable multiple keys in a single API call, this is a feature request of the KMS API rather than the client library. For feature requests for the API itself, please click the `Send Feedback` button on this [page](https://cloud.google.com/kms/docs/resources) to share feedback with the KMS API team.

**Comment by BinarSkugga** [comment]
No this is disabling a crypto key version. This is issue is about disabling the entire key: all its versions.
